/// Generated by AssetsRefGenerator on 2021/12/15
class Res {
  static const String keyspin = "assets/keyspin.png";
  static const String silverwheel = "assets/silverwheel.png";
  static const String strongbox = "assets/strongbox.png";
}
